name: CI

on: [push, pull_request]

jobs:

  build-and-test-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Lint Functions
        run: npm run lint --workspace=functions

      - name: Build Functions
        run: npm run build --workspace=functions

      - name: Test Functions
        run: npm test --workspace=functions

  web-app-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Lint Web App
        run: npm run lint --workspace=web-app

      - name: Build Web App
        run: npm run build --workspace=web-app
